### ISSUE TITLE
Plugins - ClassName on class which implements Plugin*

### ISSUE THREAD

**Issue by norrs** [dotkom/OnlineGuru#6]
At the moment it seems we don't have any clear convention if the classname which implements Plugin interface should postfix "Plugin" in it's class name or not.

I find it good to postfix Plugin on classes which implements the Plugin interface. Makes it easy to find em in IntelliJ Idea with CTRL+n "*Plugin" etc and easier to spot which one is actually implemting the plugin interface in a plugin package.

Any comments on this?

**Comment by melwil** [comment]
I agree, we just haven't thought that through properly I guess.

Many plugins contain quite a few files, and having the "actual plugin file" named correctly would perhaps cut down the necessary time to read plugins properly?

**Comment by melwil** [comment]
idea for a system to manage plugins while onlineguru is running (will require a restart of course..)!

If plugins have a generic way to be named, you can make a trigger like "!enableplugin Derp".

OnlineGuru would then look for onlineguru/src/..../plugin/plugins/derp/DerpPlugin.java

This would only work if we have a convention for naming plugin "mains" more accurately.
